export const cardDetails = [
  {
    id: 1,
    title: "Card Title 1",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 2,
    title: "Card Title 2",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 3,
    title: "Card Title 3",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 4,
    title: "Card Title 4",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 5,
    title: "Card Title 5",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 6,
    title: "Card Title 6",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 7,
    title: "Card Title 7",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
  {
    id: 8,
    title: "Card Title 8",
    image: "/images/Mockup.jpg",
    description: "Card description goes here.",
    price: "10.00 Bath",
    normalprice: "15.00 Bath",
    saveprice: "5.00 Bath",
    remaining: "5",
  },
];
